### ISSUE TITLE
The scanner is only reading Qrcodes for me, I'm using Angular version 9.1 and the latest lib version. I am using this in my app: <zxing-scanner [formats]="['QR_CODE', 'EAN_13', 'CODE_128', 'DATA_MATRIX']"></zxing-scanner>

### ISSUE THREAD

**Issue by jedisonvieira** [zxing-js/ngx-scanner#318] opened 2020-07-22 12:10 UTC
**Describe the bug**
I try to scann other formats and it doesnt work.

**Expected behavior**
Scann the other formats.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 84.0.4147.89

**Comment by odahcam** [comment] 2020-08-18 03:51
Dupe of #303

**Closed by odahcam** 2020-08-18 03:51 UTC
Labels: bug
