### ISSUE TITLE
Scann specific area

### ISSUE THREAD

**Issue by hiperiumlw** [zxing-js/ngx-scanner#172] opened 2019-02-22 15:44 UTC
Hello.

It is possible to scan specific area of the camera?
I'm working on a project, where I need to draw small rectangular on the middle of the screen and scan only on that specific area. 

The whole view will be the camera's view, but want to scan the area mentioned above.

Thanks in advance.

**Comment by santoshgund** [comment] 2019-03-09 07:18
I am also looking for the same feature. I went through the complete documentation, but I didn't find any help.

**Comment by fletchsod-developer** [comment] 2019-03-13 21:07
I ran into this same issue with multiple barcodes and am in the same boat as you guys are.

**Comment by zhanglongchina** [comment] 2019-10-13 00:24
me too  I am also looking for it, any progress?

**Comment by odahcam** [comment] 2019-10-13 20:54
Dupe of #122

**Comment by odahcam** [comment] 2019-10-13 20:55
You should take a look on #122, there's a workaround for this issue.

**Closed by odahcam** 2019-10-13 20:55 UTC
Labels: enhancement
