### ISSUE TITLE
Camera view not opened in iOS and showing the blank screen in ionic while implement zxing 

### ISSUE THREAD

**Issue by Murugan1778** [zxing-js/ngx-scanner#182] opened 2019-05-13 07:28 UTC
Hi all I was implemented zxnig/js for barcode scan.Its working well in android platform .But I am  facing the blank screen problem in iOS

**Expected behavior**
It should scan well in iOS devices.

**Smartphone:**
 - Device: [ iPhone6]
 - OS: [e.g. iOS12.2]

**Additional context**
I am getting following error.I was added camera permission in plist
![Screenshot 2019-05-13 at 12 44 26 PM](https://user-images.githubusercontent.com/42864748/57603162-9bb26680-757e-11e9-9db0-2096bcca7faf.png)

**Comment by odahcam** [comment] 2019-05-21 00:27
Please, provide reproduce steps. :)

**Comment by odahcam** [comment] 2019-05-21 00:40
@thanhphuocdang any ideas?

**Comment by thanhphuocdang** [comment] 2019-05-21 02:05
@Murugan1778, 
Please give clearly your issue, 
What framework you are living?
How do you build that ios app?
How about the OSX app running?
Steps to reproduce, please.

**Comment by manikandan07081995** [comment] 2019-05-23 04:51
@odahcam @thanhphuocdang   I am also facing the same issue. It's asking the media permission. I have given the <key>NSCameraUsageDescription</key>
  <string>My reason justifying fooling around with your camera</string>

in info.plist. But still, I am getting the same error.

**Comment by odahcam** [comment] 2019-05-23 05:59
Please, anyone send reproduction steps.

**Comment by manikandan07081995** [comment] 2019-05-23 07:11
Step 1: Created ionic project (Spec: ionic 3.20.0 version)
Step 2: Then install this npm -  **npm i @zxing/ngx-scanner@latest --save**
step 3: Import the ZXingScannerModule in app Module.
import { ZXingScannerModule } from '@zxing/ngx-scanner';
@NgModule({
 imports: [ ZXingScannerModule ] })
Step 4: Home page Html following code added.
<zxing-scanner [formats]="['QR_CODE', 'EAN_13', 'CODE_128', 'DATA_MATRIX']"></zxing-scanner>
Step 5: Ionic cordova build ios
Step 6: Open xcode project then run the workspace backend error showing. 
@zxing/ngx-scanner', 'Can\'t get user media, this is not supported.

**Comment by manikandan07081995** [comment] 2019-05-23 07:13
@odahcam, please do the above steps. But same code working while ionic serve and show in the browser.

**Comment by manikandan07081995** [comment] 2019-05-23 12:16
application open in WKWebView

**Comment by odahcam** [comment] 2019-05-23 22:45
As far as I know, `WKWebView` (I've written about it myself on Can I Use) does not supports `navigator.getUserMedia` method, which is essential in the base lib. Didn't you notice any errors or warnings in the iOS log about that?

**Comment by thanhphuocdang** [comment] 2019-05-24 03:08
Did you try with NSCameraUsageDescription before?
I suggest using cordova.plugins.diagnostic and Cordova-plugin-camera on your code for asking runtime permission.
NSCameraUsageDescription is just the asking permission message description right? I haven't used it yet.

**Comment by manikandan07081995** [comment] 2019-05-24 04:52
@odahcam  zxing-scanner - askForPermission - Can't get user media, this is not supported. This is the error I got in ios Log. Correctly said @odahcam , navigator.getUserMedia is undefined. Can you tell the alternative or solution for this issue?

**Comment by manikandan07081995** [comment] 2019-05-24 04:55
@thanhphuocdang  I tried NSCameraUsageDescription in info plist. But It not helpful.

**Comment by odahcam** [comment] 2019-05-24 05:08
Well, I don't really know how to workaround WKWebView yet, so feel free to discuss solutions here. I'll close this since it's not a 1st party issue, but a WebKit. I you find something I would be glad to document that, thanks.

**Closed by odahcam** 2019-05-24 05:08 UTC
Labels: 3rd party, investigation
