### ISSUE TITLE
Error if scanner.resetScan() is called

### ISSUE THREAD

**Issue by ScienceOfficer** [zxing-js/ngx-scanner#107] opened 2018-06-19 13:49 UTC
**Describe the bug**
If I try to call scanner.resetScan() inside the Method which is called on scanSuccess, I get the following error:

ERROR TypeError: Cannot read property 'naturalWidth' of undefined
    at BrowserQRCodeReader.push../node_modules/@zxing/ngx-scanner/esm5/zxing-ngx-scanner.js.BrowserCodeReader.prepareCaptureCanvas (zxing-ngx-scanner.js:191)

**To Reproduce**
I tried to reproduce my problem at stackblitz, but I didn't get it to work :( Sorry!

**Expected behavior**
The scanner should just stop and throw no errors.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 67

**Additional context**
I use Angular Version 6.0.2 and the Dev Version (1.2) of ngx-scanner. 

I am happy about anything that could help :)

**Comment by odahcam** [comment] 2018-06-19 15:08
StackBlitz is with some problem when installing our Angular 6 dependent version because of some third-party dependency. 😠 

The issue is here: https://github.com/zxing-js/ngx-scanner/blob/d61290aec823512d72a838b3a4fdab017b968fa6/src/app/modules/zxing-scanner/browser-code-reader.ts#L346-L347

Should be fixed in the next version. Thanks!

**Comment by ScienceOfficer** [comment] 2018-06-20 19:58
Great, thank you!

**Closed** 2018-06-27 01:37 UTC
Labels: bug
